apache/incubator-tamaya

code/api/src/main/java/org/apache/tamaya/spi/ConversionContext.java
code/api/src/test/java/org/apache/tamaya/spi/ConversionContextTest.java

Comments in ConversionContext lead me to believe that supportedFormats
should have their order maintained after import.  The HashSet that the
Builder object uses as a backer will not accomplish that goal.  This
change converts the Builder to use LinkedHashSets for supportedFormats, as
well as the object proper.
Some additional tests have been added here in pursuit of TAMAYA-288's
additional code coverage.

TAMAYA-327: Consistent signature creating ConversionContexts

---

code/spi-support/src/main/java/org/apache/tamaya/spisupport/PropertyConverterManager.java
code/spi-support/src/test/java/org/apache/tamaya/spisupport/PropertyConverterManagerTest.java

Simple copy-and-paste miss.  All the other primitives have both a simple
and array type check.  Boolean has two simple checks and no arrays.
This corrects the copy and adds a test.
I also hit "Format" on the test class so there's a bunch of whitespace changes.  I can undo that if it's stressful to anyone.

TAMAYA-329: mapBoxedType should work with boolean[]

---

code/core/src/main/java/org/apache/tamaya/core/internal/converters/CharConverter.java
code/core/src/test/java/org/apache/tamaya/core/internal/converters/CharConverterTest.java
code/core/src/test/java/org/apache/tamaya/core/internal/converters/ConverterTestsPropertySource.java

CharConverter uses paired apostrophes (') to delimit multi-character
strings and pulls the first into a Character object as needed.  That
works great, but has made it to where a single apostrophe by itself
cannot be used directly.  Entertainingly, "'''" works, but "'" throws an
exception.  This adds a simple check if the string is 1 character long
after having determined that it starts with an apostrophe.

TAMAYA-328: Let CharConverter parse a single apostrophe character

---

pom.xml

Resolves TAMAYA-330
With this configuration, I am able to build Tamaya successfully on JDK 1.8, JDK 9 and JDK 10

TAMAYA-330: Update maven plugins to support jdk9+ builds

---

code/spi-support/src/main/java/org/apache/tamaya/spisupport/propertysource/EnvironmentPropertySource.java
code/spi-support/src/test/java/org/apache/tamaya/spisupport/propertysource/EnvironmentPropertySourceTest.java

String.replaceAll(String, String) takes a regex as its first argument,
not a literal replaceable string.  The result of this is that any
single-character environment variable is converted to use the "_" key
which has special significance to the system.  Tests in the extensions
repo include some that have a single character which this change should
get working again.  I've included a test in this repo for that case as
well.

TAMAYA-340 Bugfix for regex "\\." vs literal "."

---

.travis.yml
code/api/src/main/java/org/apache/tamaya/TypeLiteral.java
pom.xml

This updates the Javadoc plugin to 3.0.1 and the JaCoCo plugin to 0.8.2. It also fixes a javadoc tag that, apparently, is not valid under JDK 11.

TAMAYA-349: Ensure Tamaya builds on JDK 11

---

code/spi-support/src/main/java/org/apache/tamaya/spisupport/EnumConverter.java
code/spi-support/src/test/java/org/apache/tamaya/spisupport/EnumConverterTest.java

Previously, EnumConverter would throw an NPE if passed a null value, but
only because of an attempted .toUpperCase() which didn't get caught.
This commit now passes null values through instead of throwing NPE.

EnumConverter works with null values

---

code/api/bnd.bnd
code/core/bnd.bnd
code/spi-support/bnd.bnd
pom.xml

Related to TAMAYA-331
These changes are mostly cosmetic, removing extraneous whitespace from some `MANIFEST.MF` entries. Some `http` URLs are also changed to `https`. The `SCM-url` entry was removed because it produced an incorrect value (and it seems not possible to have it produce a correct value).
The manifest entries also seemed to be expecting a `${buildNumber}` value, but the `buildnumber-maven-plugin` wasn't included in the maven configuration; that has now been added.

Clean up OSGi/Manifest metadata

---

code/api/pom.xml
code/core/pom.xml
code/spi-support/pom.xml
pom.xml

This enables the checkstyle plugin for the maven verify phase,
and updates the plugin to a more recent version.

TAMAYA-219: Update checkstyle plugin and configuration

---

examples/01-minimal/pom.xml
examples/02-custom-property-source/pom.xml
examples/02-custom-property-source/src/main/java/org/apache/tamaya/examples/custompropertysource/SimplePropertySource.java
examples/02-custom-property-source/src/main/java/org/apache/tamaya/examples/custompropertysource/SimplePropertySourceProvider.java
examples/11-distributed/pom.xml

This enforces checkstyle rules on the example projects and makes a few
minor adjustments to bring the custom-property-source project in line
with the formatting rules.

TAMAYA-379: Enforce checkstyle rules on the example projects

---

buildconfigurations/src/main/resources/checkstyle/style.xml
code/core/src/main/java/org/apache/tamaya/core/internal/BannerManager.java
code/core/src/main/java/org/apache/tamaya/core/internal/OSGIServiceLoader.java

This changes the ConstantName, MethodName and TypeName checkstyle rules
such that the default (and standard) Java formatting rules are followed.
By changing the checkstyle configuration in this way, the only required code modification was replacing the constant `log` with `LOG`.

TAMAYA-379: Tighten checkstyle rules for main codebase

---

buildconfigurations/src/main/resources/checkstyle/style.xml

The `illegalClasses` section is for non-static imports (e.g. `import org.junit.Assert`), and the `illegalPkgs` section covers static imports (e.g. `import static org.junit.Assert.assertTrue`).

TAMAYA-219: Prohibit non-AssertJ test assertions

---

code/api/src/main/java/org/apache/tamaya/spi/ServiceContextManager.java
code/core/src/main/java/org/apache/tamaya/core/OSGIActivator.java

We use the thread's classloader as a key into a hashmap to find the
serviceloader for a given configuration.  In OSGi, we have separate
classloaders for the CoreConfigurationBuilder,
DefaultConfigurationBuilder, and ServiceContextManager.  That confusion
prevents the simple case from finding a match in the hashmap that can
load a particular ServiceContext.  Since
CoreConfiguation/DefaultConfiguration already uses the static class's
classloader during <init>, this PR allows the OSGIActivator to point
that classloader at the relevant OSGIServiceContext.
With these changes I was able to get the bundles to start in an Apache Karaf instance.

TAMAYA-383 Let OSGi skip thread classloader key

---

.travis.yml
code/core/pom.xml
pom.xml

It's hard to actually test this, but there are a few adjustments here that should help. 
First, JaCoCo wasn't actually turned on for the `tamaya-core` module (overriding the `argLine` had removed JaCoCo's own override). 
Second, JaCoCo had to be manually invoked, by moving the configuration from `<pluginManagement>` to `<plugins>`, it is now tied to the `mvn verify` stage.
Next, it seems that the `SONAR_TOKEN` can be interpolated as shown in the adjustment to `.travis.yml`, and perhaps that is required
Finally, I added a number of sonar-specific properties directly to the `pom.xml` file.
@ottlinger has the SonarCloud token, so you might be able to test this locally. Or, you can just merge it and see how it works. My experience with SonarCloud integration involves gradle, so I don't have a …

TAMAYA-277 adjust sonar configuration

---

buildconfigurations/src/main/resources/checkstyle/style.xml
pom.xml

This upgrades the checkstyle plugin to 8.19
The exclusion code in the maven configuration are no longer relevant,
and the style.xml file itself needed some minor modifications that go
along with the upgrade to the 8.x series

TAMAYA-387 Upgrade checkstyle plugin

---

.travis.yml

As suggested by @bellingard in [this comment](https://github.com/apache/incubator-tamaya/commit/98bc730a4dbfd257fef02abf59c7f31397e1abef#r33292801), this simplifies the sonar configuration and ensures that it runs in the JDK8 environment on Travis-CI

TAMAYA-77: Change sonar config to use mvn style for analysis

---

code/api/src/main/java/org/apache/tamaya/spi/ServiceContextManager.java
code/spi-support/src/main/java/org/apache/tamaya/spisupport/propertysource/PropertiesResourcePropertySource.java
code/spi-support/src/main/java/org/apache/tamaya/spisupport/propertysource/SystemPropertySource.java

The Sonar analysis doesn't like the use of `volatile` on fields. This change removes the `volatile` keyword in places where the field doesn't need to be marked as `volatile`. That is, these are cases where the field is, in fact, `final`.
Where appropriate, this also adjusts the field formatting to align with checkstyle rules.

LHF: remove unnecessary volatile keywords

---

code/core/src/main/java/org/apache/tamaya/core/internal/OSGIServiceLoader.java

This opens a `BufferedReader` in a try-with-resources block to ensure that the resource is properly closed in the event of an exception.

TAMAYA-277: LHF: use try-with-resources with BufferedReader

---

.travis.yml

There is an ongoing discussion about this on the mailing list, but if it is determined that a failed Sonar build should not fail the entire CI task, this is a PR that should do the trick.
Supersedes #51

TAMAYA-277: Don't fail builds because of Sonar

---

code/core/src/test/java/org/apache/tamaya/core/internal/CoreConfigurationProviderTest.java
code/core/src/test/java/org/apache/tamaya/core/internal/CoreConfigurationTest.java
code/spi-support/src/test/java/org/apache/tamaya/spisupport/DefaultConfigurationBuilderTest.java
code/spi-support/src/test/java/org/apache/tamaya/spisupport/DefaultConfigurationSnapshotTest.java
code/spi-support/src/test/java/org/apache/tamaya/spisupport/DefaultMetaDataProviderTest.java
code/spi-support/src/test/java/org/apache/tamaya/spisupport/PropertySourceChangeSupportTest.java

This adds assertions to tests that lacked any, as reported by Sonar.

TAMAYA-277: Add test assertions
